#:kivy 1.0
#:include ./templates/screens/MainScreen.kv
#:include ./templates/screens/ProjectManagerScreen.kv
#:include ./templates/screens/LabelManagerScreen.kv
#:include ./templates/screens/SettingsScreen.kv

<ScreenManagement>:
    MainScreen:
        name: 'main_screen'
    ProjectManagerScreen:
        name: 'project_manager_screen'
    LabelManagerScreen:
        name: 'label_manager_screen'
    SettingsScreen:
        name: 'settings_screen'
        